backend:
  name: github
  repo: kimiikonen-lab/ambitus-site
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Riassunto", name: "summary", widget: "text", required: false}
      - {label: "Bozza", name: "draft", widget: "boolean", default: false}
      - {label: "Corpo del testo", name: "body", widget: "markdown"}
